export const ADD_CURRENCIES_RATE_TO_WISHLIST =
  "ADD_CURRENCIES_RATE_TO_WISHLIST";

export const ADD_ALL_CURRENCIES_RATE_TO_WISHLIST =
  "ADD_ALL_CURRENCIES_RATE_TO_WISHLIST";

export const REMOVE_CURRENCIES_RATE_TO_WISHLIST =
  "REMOVE_CURRENCIES_RATE_TO_WISHLIST";
