export const ADD_CURRENCIES_RATE_TO_WATCHLIST =
  "ADD_CURRENCIES_RATE_TO_WATCHLIST";

export const ADD_ALL_CURRENCIES_RATE_TO_WATCHLIST =
  "ADD_ALL_CURRENCIES_RATE_TO_WATCHLIST";

export const REMOVE_CURRENCIES_RATE_TO_WATCHLIST =
  "REMOVE_CURRENCIES_RATE_TO_WATCHLIST";
